/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "techwitzsapi",
            "endpoint": "https://zhk8szwz97.execute-api.ap-southeast-1.amazonaws.com/feature",
            "region": "ap-southeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-southeast-1:7f9bb6f7-4421-4a81-8018-1a0b5249e9c9",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_zsnjT1YkS",
    "aws_user_pools_web_client_id": "2i6j3gm8pqou3pna8ujb2sqaas",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_dynamodb_all_tables_region": "ap-southeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "invoice-feature",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "itemscategory-feature",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "items-feature",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "itemswishlist-feature",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "maxdata-feature",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "purchaseorder-feature",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "salesorder-feature",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "tenant-feature",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "user-feature",
            "region": "ap-southeast-1"
        }
    ]
};


export default awsmobile;
