name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: echo "Hello"
    - run: git remote set-url --add --push origin https://github.com/techwitzs-ventures/agros-website-test.git 
    - run: git branch -M main
    - run: git push -u origin main
    
