name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: git remote add github https://varanasiramesh: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@github.com/startup-ventures/agros-website.git
    - run: git remote set-url --add --push origin https://varanasiramesh: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@github.com/startup-ventures/agros-website.git
    - run: git push -f -u github main
