name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: echo "Hello"
    - run: git remote add origin https://git.harness.io/xtFPfyCaR_Crf1m40r40zQ/default/AgrosHub_App/agros-website.git
    - run: git branch -M main
    - run:  git push -u origin main
    
